kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  # TODO will break on multi node setups (or at least make one master more master-y than the others)
  # possibly use split hoizon dns in the future
  KUBERNETES_SERVICE_HOST: "10.10.10.31"
  KUBERNETES_SERVICE_PORT: "6443"
