apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: foo-nginx
  labels:
    app: foo-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: foo-nginx
  template:
    metadata:
      labels:
        app: foo-nginx
    spec:
      containers:
      - name: foo-nginx
        image: nginx
        ports:
        - containerPort: 80
