apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-config
  namespace: lecture-obs
data:
  # language=json
  .filebrowser.json: |
    {
       "port": 80,
       "baseURL": "",
       "address": "",
       "log": "stdout",
       "database": "/database.db",
       "root": "/srv",
      "noauth": true
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: lecture-obs
  labels:
    app: browser
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
        - name: browser
          image: filebrowser/filebrowser:v2.23.0
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: /srv
              name: obs-video
            - mountPath: /.filebrowser.json
              name: config
              subPath: .filebrowser.json
      volumes:
        - name: obs-video
          persistentVolumeClaim:
            claimName: obs-video
        - name: config
          configMap:
            name: browser-config
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: lecture-obs
spec:
  selector:
    app: browser
  ports:
    - port: 80
      name: web
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: browser
  namespace: lecture-obs
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
spec:
  rules:
    - host: obs-browser.771.blue
      http:
        paths:
          - backend:
              service:
                name: browser
                port:
                  name: web
            pathType: Prefix
            path: /
