apiVersion: v1
kind: Namespace
metadata:
  name: mc-router
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-router
  namespace: mc-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-watcher
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-router-services-watcher
subjects:
- kind: ServiceAccount
  name: mc-router
  namespace: mc-router
roleRef:
  kind: ClusterRole
  name: services-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: mc-router
  annotations:
    metallb.universe.tf/allow-shared-ip: ipv4s-are-expensive
spec:
  type: LoadBalancer
  ports:
  - targetPort: proxy
    name: proxy
    port: 25565
  selector:
    app: mc-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-router
  name: mc-router
  namespace: mc-router
spec:
  selector:
    matchLabels:
      app: mc-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mc-router
    spec:
      serviceAccountName: mc-router
      containers:
      - image: itzg/mc-router:1.31.0
        name: mc-router
        args: ["--in-kube-cluster"]
        ports:
        - name: proxy
          containerPort: 25565
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: 50Mi
            cpu: "100m"
          limits:
            memory: 100Mi
            cpu: "250m"
