apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ansible-semaphore
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ansible-semaphore
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
