resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 17.17.1
    releaseName: redis
    namespace: grindstone-stats
    valuesFile: redis-values.yaml
