apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-cd-exam-notify
  namespace: discord-cd-exam-notify
spec:
  selector:
    matchLabels:
      app: discord-cd-exam-notify
  template:
    metadata:
      labels:
        app: discord-cd-exam-notify
    spec:
      initContainers:
        - name: save-data
          image: ghcr.io/jemand771/discord-cd-exam-notify:1.0.0
          command:
            - sh
            - -c
            - cp -rt /app-mnt /app/*
          volumeMounts:
            - mountPath: /app-mnt
              name: data
      containers:
        - name: discord-cd-exam-notify
          image: ghcr.io/jemand771/discord-cd-exam-notify:1.0.0
          envFrom:
            - secretRef:
                name: discord-cd-exam-notify
          env:
            # this is required for logs to work properly
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - mountPath: /app
              name: data
          resources:
            requests:
              memory: 200Mi
              cpu: 10m
            limits:
              memory: 1Gi
              cpu: 100m
      volumes:
        - name: data
          emptyDir: {}
